name: nox

on: push

jobs:
  nox_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: pipx install nox uv
    - run: nox

  nox_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - run: pipx install nox uv
    - run: nox -p 3.13  # Only test on 3.13 because Windows CI is so slow.

  nox_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - run: pipx install nox uv
    - run: nox
