name: nox

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pipx install nox uv
    - name: nox
      run: |
        nox

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pipx install nox uv
    - name: nox
      run: |
        nox
