name: Run lint and tests with nox

on: push

jobs:
  nox_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: pipx install nox uv
    - run: nox
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ github.job }}-${{ strategy.job-index }}
        path: .coverage.*
        include-hidden-files: true
        if-no-files-found: error

  nox_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - run: pipx install nox uv
    - run: nox -p 3.13  # Only test on 3.13 because Windows CI is so slow.
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ github.job }}-${{ strategy.job-index }}
        path: .coverage.*
        include-hidden-files: true
        if-no-files-found: error

  nox_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - run: pipx install nox uv
    - run: nox
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ github.job }}-${{ strategy.job-index }}
        path: .coverage.*
        include-hidden-files: true
        if-no-files-found: error

  coverage:
    runs-on: ubuntu-latest
    needs: [nox_linux, nox_macos, nox_windows]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        pattern: coverage-*
        merge-multiple: true
    - run: pipx install nox uv
    - run: nox -s cover
